# spring이 application.yml을 읽는 순서
# 0. bootstrap.yml - MSA Configuration Server 연동 시 사용
# 1. application.yml
# 2. application-{profile}.yml
# 프로필이 존재하지않을때 real1 -> application-real1.yml
spring:
  thymeleaf:
    prefix: classpath:/templates-local/
    suffix: .html
  config:
    import: classpath:common.yml
# test - 테스트를 돌리는 환경
# local - 내컴퓨터
# dev - 개발서버 - 내부 관계자들이 테스트목적으로
# qa - 품질검증서버 - 실제 운영환경과 동일한 환경에서 최종 테스트 목적
# prod - 운영서버 - 실제 사용자들이 사용하는 서버

# 인텔리제이에서 할 때
#  - edit configurations - active profiles
# 실제 배포할 때 - 환경 변수로 제어
# - java -jar -Dspring.profiles.active=prod xxx.jar
server:
  port: 80
